# Build from source.
name: build_macos
on: [push, pull_request]
permissions: read-all
jobs:
  build_ubuntu:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
        - os: macos-13
          configure_options: ''
        - os: macos-14
          configure_options: ''
        - os: macos-15
          configure_options: ''
    steps:
    - uses: actions/checkout@v4
    - name: Install build dependencies
      run: |
        brew update -q
        brew install -q autoconf automake gettext gnu-sed libtool pkg-config || true
        brew link --force gettext
        ln -s /usr/local/bin/glibtoolize /usr/local/bin/libtoolize
    - name: Download test data
      run: |
        if test -x "synctestdata.sh"; then ./synctestdata.sh; fi
    - name: Building from source
      env:
        CC: ${{ matrix.compiler }}
      run: |
        tests/build.sh ${{ matrix.configure_options }}
    - name: Run tests
      run: |
        tests/runtests.sh
